### ISSUE TITLE
FR: flag / report inappropriate comments in frontend

### ISSUE THREAD

**Issue by johanneslamers** [engram-design/Comments#1]
Flag / report inappropriate comments in frontend. 
 - After x amount of flags remove comment. (like disqus)

**Comment by engram-design** [comment]
Implemented in 0.1.1. Doesn't delete the comment, but instead provide you with a `isFlagged` variable. That way, you can decide what you'd like to do with the flagged comment. 

You may want to simply exclude it (and all replies), or you might want to keep any replies, but have a '[comment flagged as inappropriate]' - which is the default. My reasoning behind this is the same reason we don't delete a comment - it should preserve any replies.

Have a look at the updated wiki - https://github.com/engram-design/Comments/wiki/Comment-ElementType or the updated template incorporating this - https://github.com/engram-design/Comments/blob/master/comments/templates/_forms/templates/comment.html#L76

Closing for now - let me know if you have any further suggestions.
