### ISSUE TITLE
No FR... just have to say the plugin works great!!! 

### ISSUE THREAD

**Issue by johanneslamers** [engram-design/Comments#13]

**Comment by engram-design** [comment]
Thanks @johanneslamers! Feel free to keep those FR coming! :)

**Comment by johanneslamers** [comment]
Got some other plugin idea's if you like :)

**Comment by engram-design** [comment]
They're always welcome - would love to hear them!

**Comment by johanneslamers** [comment]
can I send you an email?

Verstuurd vanaf mijn iPhone

**Comment by engram-design** [comment]
Yep! Josh at engramdesign.com.au

**Comment by johanneslamers** [comment]
You can close this issue :-)
