### ISSUE TITLE
FR: Email author after comment

### ISSUE THREAD

**Issue by johanneslamers** [engram-design/Comments#2]
Notify / email the author of the page entry after a comment. 
 - Maybe you can use Postmaster for it. https://github.com/objectivehtml/Postmaster-for-Craft-CMS
 - Notify email of new posts.
 - Notify me of follow-up comments via email checkbox in comment form.
 - Notify me of new posts via email checkbox in comment form.
 - Opt out for notifications in user profile settings

**Comment by engram-design** [comment]
Nice one! It'd be great if there was some way to integrate a plugin with another somehow!

**Comment by johanneslamers** [comment]
Postmaster has some API's you can use. https://github.com/objectivehtml/Postmaster-for-Craft-CMS/wiki/Developer-API

**Comment by engram-design** [comment]
Yep, also looking at using [Sprout Invisible Capture](http://sprout.barrelstrengthdesign.com/craft-plugins/invisible-captcha) but is much more of a required plugin setup, because it's reliant on it for core features...

**Comment by johanneslamers** [comment]
![schermafdruk 2015-03-23 10 14 53](https://cloud.githubusercontent.com/assets/4696315/6776983/8befa88e-d145-11e4-8947-968aa9b064a7.png)

**Comment by leeaston** [comment]
Be nice if the email notification were built-in to the comments plugin - imo, less dependencies the better.

**Comment by engram-design** [comment]
Thats exactly right. The point I was trying to make above was that this should really be a built-in feature. I'd rather not have a 'download Postmaster and you can do this' sort of thing. I could potentially look at bundling Postmasters with Comments, but this seems tricky from both a licensing and practicality point of view.

Unless someone has a better option to integrate, this'll be a built-in core feature. However, it's a reasonably time consuming implementation, so will push it down the roadmap list for now. I'd like to focus on the crucial items (security) before release!

**Comment by c0py** [comment]
Just to add my 2 cents.

Id prefer to see this plugin provide a method such as using events to let other plugins do the emailing/notification stuff. Let the comments plugin do comments, then the emailers, notifier types plugins can just do their stuff.

So just to clarify, don't add support for postmaster, let postmaster add support for the comments plugin.

:)

**Comment by engram-design** [comment]
I like your thinking @c0py! For now, this'll be likely something I'll add after release.

**Comment by engram-design** [comment]
Notifications were added in [0.4.1](https://github.com/engram-design/Comments/releases/tag/0.4.1)
