### ISSUE TITLE
FR: Stick up upvoted comments

### ISSUE THREAD

**Issue by johanneslamers** [engram-design/Comments#20]
You can stick up outstanding comments and grant them extra viewership. For popular comments, they will appear in the upvoted list so others will know what is good for them.

**Comment by johanneslamers** [comment]
Users can tag their own location as they leave a comment. It is an interesting way to find out where all of those comments come from.

**Comment by engram-design** [comment]
You can query by votes as of [version 0.4.0](https://github.com/engram-design/Comments/releases/tag/0.4.0). This should allow you to either fetch upvoted comments to print out separately, or simply order them.

```
{{ craft.comments.form(entry.id, { 'order': 'upvote desc' }) }}
or
{{ craft.comments.form(entry.id, { 'order': 'downvote desc' }) }}
```
