### ISSUE TITLE
FR: Easy switch from latest comments view to popular comments

### ISSUE THREAD

**Issue by johanneslamers** [engram-design/Comments#22]
Switch comment ordering in frontend from latest comments tot popular comments.

**Comment by engram-design** [comment]
While I haven't provided this in the templates, this can be easily done now via:

```
{% block content %}

    {% set params = {
    	order: 'upvote desc',
    } %}

    {{ craft.comments.form(entry.id, params) }}

{% endblock %}
```

**Comment by engram-design** [comment]
Closing this for now - this is in the realm of templating, so really up to the integrator of this plugin. All the parts are there to make this possible.
