### ISSUE TITLE
stristr(): Empty needle

### ISSUE THREAD

**Issue by themccallister** [engram-design/Comments#28]
I've been having the user report some comments have not been submitting successfully, I logged in as as admin and tried to enter the following text:

`Testing the commenting flagging.`

The following error was returned:

https://www.dropbox.com/s/ag0bzt4x7883ju5/Screenshot%202015-08-03%2017.48.17.png?dl=0

**Comment by engram-design** [comment]
Looks as though this will occur if there is an empty line in the Comment Moderation settings. Fixed in the latest master.

**Comment by themccallister** [comment]
I will pull this version and test to verify, then close out the issue.

Thanks for the fast turn around!

**Comment by engram-design** [comment]
No worries - let me know if it doesn't fix this issue.

**Comment by themccallister** [comment]
This solved that issue, I think. However, it did introduce another. I'm going to post as a separate issue for tracking purposes.

**Comment by themccallister** [comment]
Solved the issue! Thanks!
