### ISSUE TITLE
Latest update seems to have broken several things.

### ISSUE THREAD

**Issue by lettie16** [engram-design/Comments#33]
Firstly

Trying to get property of non-object 
/homepages/3/d272256762/htdocs/crafttest/craft/plugins/comments/controllers/CommentsController.php(116)
`if ($fieldSettings->requireModeration) {`

Seems the moderation lightswitch in the settings has been removed in the CMS.

If I comment out the above we get:

Trying to get property of non-object 
/homepages/3/d272256762/htdocs/crafttest/craft/plugins/comments/controllers/CommentsController.php(134)
`if (!$fieldSettings->allowAnonymous && !$commentModel->userId) {`

Any ideas?

**Comment by engram-design** [comment]
@lettie16 Please update to the [0.3.8](https://github.com/engram-design/Comments/releases/tag/0.3.8) which fixes a lot of bug, including this one. Feel free to reopen if you continue to have issues!
