### ISSUE TITLE
Error with Craft\CommentsHelper::deleteAction()

### ISSUE THREAD

**Issue by ianisted** [engram-design/Comments#34]
I've setup Comments, and added it to the page using the standard example. It loaded on the page and let me add a comment, but once a comment was in the system I could no longer load that page. The template is giving the following error.

```Non-static method Craft\CommentsHelper::deleteAction() should not be called statically, assuming $this from incompatible context```

If I mark the comment as Trashed in the admin area the page will load and show the comment as deleted. If I set it back, I get the same error.
[PHP error.pdf](https://github.com/engram-design/Comments/files/32710/PHP.error.pdf)

**Comment by ianisted** [comment]
These problems seem to be do with the action URLs on the front-end.
Removing this section of code from the `comment-approved.html` template solves the problem.

```
			{% if currentUser %}
				<div class="dropdown options-dropdown">
					<a href="#" class="dropdown-toggle" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">Options <span class="caret"></span></a>

					<ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
						{% if comment.userId and not comment.isClosed %}
							<li role="presentation">
								<a href="#" class="comment-edit">
									<span class="glyphicon glyphicon-edit"></span>Edit
								</a>
							</li>

							<li role="presentation">
								<a href="{{ comment.deleteActionUrl }}" class="comment-delete">
									<span class="glyphicon glyphicon-remove"></span>Delete
								</a>
							</li>
						{% endif %}

						<li role="presentation">
							{% if comment.flagActionUrl %}
								<a href="{{ comment.flagActionUrl }}" class="comment-flag">
									<span class="glyphicon glyphicon-flag"></span>Flag as inappropriate
								</a>
							{% else %}
								<span class="static-label comment-flag">
									<span class="glyphicon glyphicon-flag"></span>Flagged as inappropriate
								</span>
							{% endif %}
						</li>
					</ul>
				</div>
			{% endif %}
```

**Comment by engram-design** [comment]
I'll have a look into this, although can't seem to reproduce. What PHP version are you running?

**Comment by ianisted** [comment]
Thanks for the quick reply. I'm running version 5.6.10

**Comment by madebyshape** [comment]
I'm also running in to this issue. Running latest version of comments and also Craft Pro 2.5.2767. I'm using custom templates btw, but they have been copied direct from the /_templates/ folder in comments

**Comment by engram-design** [comment]
@madebyshape Well timed - about to push a fix for this!

**Comment by madebyshape** [comment]
Perfect! :+1: :100:

**Comment by engram-design** [comment]
Check out the latest master for this fix. I'm bundling a few other updates before a release, but this should sort you out in the meantime. Closing for now.
