### ISSUE TITLE
code license

### ISSUE THREAD

**Issue by lukeholder** [engram-design/Comments#4]
Hi, is there a license for the plugin? MIT?

**Comment by engram-design** [comment]
No enforced license yet, but when it does, it'll align to MIT.

**Comment by lukeholder** [comment]
thanks!

**Comment by lukeholder** [comment]
If you can put MIT licence on the repo, i would love to contribute.

**Comment by engram-design** [comment]
Done!

**Comment by engram-design** [comment]
It should be noted that when the Craft plugin store is released, I plan to make this available through that. I'm no license guru - so maybe MIT isn't the best fit for this. Just wanted to keep you informed in case that doesn't work for you for whatever reason.
