### ISSUE TITLE
When creating a comment admin/comments becomes inaccessible

### ISSUE THREAD

**Issue by MaximSiebert** [engram-design/Comments#40]
Once I create a comment admin/comments becomes inaccessible, i get:

`Internal Server Error – Property "Craft\ElementRecord.elementType" is not defined.`

**Comment by engram-design** [comment]
Are you able to provide a full stack trace (screenshot) of the error?

**Comment by MaximSiebert** [comment]
Sorry not sure what exactly you'd like, here's what im getting and the craft.log file

<img width="1552" alt="screen shot 2016-04-26 at 9 00 24 pm" src="https://cloud.githubusercontent.com/assets/4451296/14838709/f858e6f6-0bf1-11e6-81ca-e701a71c1baa.png">
<img width="585" alt="screen shot 2016-04-26 at 9 00 02 pm" src="https://cloud.githubusercontent.com/assets/4451296/14838711/fc9c2110-0bf1-11e6-80ad-aabcc0d017a6.png">

**Comment by engram-design** [comment]
Do you have `devMode` on? That log file is sufficient though, cheers.

I do apologise for that - a regression on my behalf, and simply forgot to push a fix for this. Have a look at the latest master, and that should get you going.

**Comment by MaximSiebert** [comment]
Thanks!
