### ISSUE TITLE
# of comments?

### ISSUE THREAD

**Issue by chadcrowell** [engram-design/Comments#41]
I looked through the docs but can't seem to find if there is a tag I can use in my entries loop to show the number of comments currently made against an entry. Does that exist?

**Comment by engram-design** [comment]
Hi there - apologies that its not immediately clear, I'll tweak the docs. You're after the `all` function, for example:

```
{% for entry in craft.entries.section('news') %}
    {{ craft.comments.all({ element: entry }) | length }}
{% endfor %}
```

**Comment by chadcrowell** [comment]
Thanks, that helps. However, within my loop I am getting the total comment count for all discussions somehow. 

http://d.pr/i/kYZ1

`{% for discussion in discussions %}
	<tr>
		<td>
			<a href="{{ discussion.url }}">{{ discussion.title }}</a>
		</td>
		<td>
			{{ discussion.author.fullName }}
		</td>
		<td>
			{{ discussion.postDate|date('F j, Y') }} at {{ discussion.postDate|date('H:i a') }}
		</td>
		<td>
			{{ craft.comments.all({ element: discussion })|length }}
		</td>
	</tr>
{% endfor %}`

**Comment by engram-design** [comment]
Ah - sorry about that, the templating code should be:

```
{% for entry in craft.entries.section('news') %}
    {{ craft.comments.all({ elementId: entry.id }) | length }}
{% endfor %}
```

**Comment by chadcrowell** [comment]
Thank you, thats it!

**Comment by jsunsawyer** [comment]
For anyone looking for an updated solution to this, you can do the following.

`{{ craft.comments.fetch().owner(entry).all() | length }}`
