### ISSUE TITLE
Order entries by latest comments

### ISSUE THREAD

**Issue by iparr** [engram-design/Comments#42]
#41 explains how to display the number of comments per entry.

I'm wondering how you'd then list the entries in the order of the lastest comment.

i.e. The entry that has last been commented on first and the entry that has not been commented on / has received a comment furthest ago, last.

Regardless: It's a great little project this. Thank you.

**Comment by engram-design** [comment]
Thats pretty straightforward - you would do something like this:
```
{% set comments = craft.comments.all({
    order: 'dateCreated desc',
}) %}

{% for comment in comments %}
    {{ comment.element.title }}
{% endfor %}
```

Which will print out the entry title in the order of the last comments. The above however will list each entry per comment - so if you have 20 comments on an entry, it'll print that out 20 times.

For a combined list that only lists entries once, you'll do:

```
{% set comments = craft.comments.all({
    order: 'dateCreated desc',
}) %}

{% set commentEntries = [] %}
{% for comment in comments if comment.element.id not in commentEntries %}
    {% set commentEntries = commentEntries | merge([comment.element.id]) %}

    {{ comment.element.title }}
{% endfor %}
```
