### ISSUE TITLE
FR: Better control permissions for logged in users

### ISSUE THREAD

**Issue by benjolabs** [engram-design/Comments#48]
Right now logged-in non-admin users can edit / delete other people's comments.
I can of course hide those options in the comment templates based on `currentUser.id` and `comment.userId`, but the plugin controller actions remain vulnerable.

I think that could be an issue for sites that allow user registrations with limited permissions.

**Comment by engram-design** [comment]
Totally agree. Functionality added and generally improved in [0.4.5](https://github.com/engram-design/Comments/releases/tag/0.4.5).
