### ISSUE TITLE
Attaching to Matrix returns error

### ISSUE THREAD

**Issue by tosegard** [engram-design/Comments#51]
First off, great plugin! It works when I attach it to an entry, but I would like to attach it to matrix blocks within the entry. When I do though, I receive the following error:

**Internal Server Error
Property "Craft\MatrixBlockModel.author" is not defined.**

My code within my block loop is:
`
{% set params = {order: 'dateCreated asc',} %}
{{ craft.comments.form(block.id, params) }}`

**Comment by engram-design** [comment]
Cool idea! I haven't testing things out with Matrix, so there's bound to be a few issues like that. I'll test and organise support for this.

**Comment by tosegard** [comment]
@engram-design Awesome! Glad I could contribute, I was worried you had already implemented this and I was just missing something.

**Comment by engram-design** [comment]
I've put some checks in place for comments on Matrix (and other fields with an owner) in [0.4.6](https://github.com/engram-design/Comments/releases/tag/0.4.6), but please re-open this issue (or create a new one) if you have any more issues.
