### ISSUE TITLE
Can't view the permissions tab in the admin comment section 

### ISSUE THREAD

**Issue by AndrewStaroscik** [engram-design/Comments#54]
When I click on the Permissions tab I get a Template error: Impossible to invoke a method ("getAllGroups") on a null variable in 

.../craft/plugins/comments/templates/permissions.html(57)

I am running craft personal v 2.6.2945 locally on MAMP Pro

**Comment by andreasbecker** [comment]
same here. I run Craft Client 2.6.2945 on MAMP Pro

**Comment by engram-design** [comment]
Sorry for the delay in fixing this - fixed in [0.4.7](https://github.com/engram-design/Comments/releases/tag/0.4.7).
