### ISSUE TITLE
EntryModel.owner is undefined

### ISSUE THREAD

**Issue by wwas** [engram-design/Comments#56]
I have build a Blog. Now I've tried to add the commenting function with Comments.

I use the absolute basic template: https://github.com/engram-design/Comments/blob/master/examples/standard/standard.html

The call in my Tpl:
```
{% set params = {
   order: 'dateCreated asc'
} %}

{{ craft.comments.form(entry.id) }}
```

Until here everything is fine. When I want so send the comment, I always get this Error:

Property "Craft \ EntryModel.owner is undefined.
The "Comments" Plugin use EntryModel.owner when I want so submit a comment on any entry. Now the problem is that {{ entry.owner }} is undefined. But how can I define the {{ entry.owner }}?

I know this is a noobie Question, but how can I fix this?

**Comment by engram-design** [comment]
Sorry for the delay in fixing this - fixed in [0.4.7](https://github.com/engram-design/Comments/releases/tag/0.4.7).
