### ISSUE TITLE
Basic templating help

### ISSUE THREAD

**Issue by robinbeatty86** [engram-design/Comments#67]
Hi, I'm very new to working with Craft and I'm trying to set up a simple anonymous guest comments functionality on a client's blog entry page. Could anyone give me a hand? The code from the included 'standard.html' is in, but when I submit a test comment I get an error:

![screen shot 2017-01-06 at 15 00 31](https://cloud.githubusercontent.com/assets/24960809/21721605/ef3d942a-d420-11e6-9faf-45f7f0fead47.png)

I'm assuming I'm missing some crucial params and/or reference to the 'element.id' but not clear what this is... The craft handle for the section I want to use this in is 'blog'. 

Here's what's in my template:

THANKS!

`{% set params = {
			order: 'dateCreated asc',
		} %}

		{{ craft.comments.form(blog.id, params) }}

		<script src="https://code.jquery.com/jquery-2.1.3.min.js"></script>
		<script>
		//
		// Below is the most minimal non-ajax JS to get started with. Mainly used to toggle
		// element such as the edit comment form, inline-reply form and showing/hiding replies.
		//
		$(document).ready(function() {
			// Toggle to show/hide replies
			$(document).on('click', 'a.comment-toggle', function(e) {
				e.preventDefault();
				$(this).parents('.comment-single:first').find('.comments-list:first').toggle();
			});
			// Toggle to show/hide reply form
			$(document).on('click', 'a.comment-reply', function(e) {
				e.preventDefault();
				$(this).parents('.comment-single:first').find('.comment-form').toggle();
			});
			// Handle editing
			$(document).on('click', 'a.comment-edit', function(e) {
				e.preventDefault();
				// Simply hides text and shows form
				$(this).parents('.comment-text').find('.comment-content').hide();
				$(this).parents('.comment-text').find('.edit-comment-form').show();
			});
		});
		</script>`

**Comment by robinbeatty86** [comment]
Ah, fixed it! should have been 'entry.id' not 'blog.id'. Works like a charm.

**Comment by engram-design** [comment]
Hey @robinbeatty86 Glad you sorted it - beat me to it!
