### ISSUE TITLE
level parameter missing in docs

### ISSUE THREAD

**Issue by bymayo** [engram-design/Comments#68]
I'm using the custom template method and been banging my head to try and figure out how to only output the main comments, not replies.

On your docs there is no 'level' parameter (https://github.com/engram-design/Comments/wiki/12.-Comment-Element) could this be added? As it does work.

**Comment by lukepearce** [comment]
Did you find a solution for this in the end? I've just taken a look inside `CommentsVariable.php` to see what criteria was being used to fetch the comments and can see a `level` being used. (line 27)

```php
$criteria = array_merge($criteria, array(
   'elementId' => $element->id,
   'level' => '1',
));
```

**Comment by bymayo** [comment]
@lukepearce Yeah adding the limit option worked fine for me.

`{% set commentParams = {
	elementId: entry.id, 
	limit: 12,
	order: 'dateCreated desc',
	level: 1
} %}`

**Comment by engram-design** [comment]
Actually, the default behaviour is to only output the top-level comments, unless you specify the show all, all certain levels. This is shown in the snippet from @lukepearce. However, there was an issue until the [latest master](https://github.com/engram-design/Comments/archive/master.zip) that caused child comments to be shown anyway.

But you can also change this using the params with your form:
```
{% set params = {
	limit: 10,
	level: '999'
} %}

{{ craft.comments.all(params) }}
```

And technically `level` is an option for any element (its inherited by any element type), but I'll add this into the documentation.
