### ISSUE TITLE
FR: Display number of comments

### ISSUE THREAD

**Issue by johanneslamers** [engram-design/Comments#8]
Would like to have a twig tag to display the number of comments in an entry.

**Comment by engram-design** [comment]
You could use something like:

```
{% set params = {
	entryId: entry.id
} %}

{{ craft.comments.all(params) | length }}
```

**Comment by engram-design** [comment]
Closing. Please reopen if the example doesn't solve your issue.

**Comment by readio** [comment]
Came across this issue when looking for a solution to display the comment count. The above code didn't work, but looking at the latest wiki I figured out I needed to use `elementId`

```
{% set params = {
    elementId: entry.id
} %}

{{ craft.comments.all(params) | length }}
```

**Comment by engram-design** [comment]
Ah - yes I think that got changed quite quickly after that, when we enabled commenting on any elements, not just entries. Thanks!

**Comment by davecoggins** [comment]
Has this syntax changed in Craft 3?
I'm currently getting an error:
`Setting unknown property: verbb\comments\elements\db\CommentQuery::elementId`

Comments v1.6.2, Craft 3.4.12

Thanks in advance

**Comment by engram-design** [comment]
@davecoggins Yep, its now `ownerid`

```
{# Fetch comments created for an element with an ID of 1 #}
{% set comments = craft.comments.fetch()
    .ownerId(1)
    .all() %}
```

See https://verbb.io/craft-plugins/comments/docs/getting-elements/comment-queries#ownerId

**Comment by davecoggins** [comment]
Perfect thanks!
